// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "这是第四幕");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_puhui18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_circle3 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_circle3, &ui_img_1758698815);
    lv_obj_set_width(ui_circle3, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_circle3, LV_SIZE_CONTENT);    /// 300
    lv_obj_set_align(ui_circle3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_circle3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_circle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_circle3, 350);

    ui_Button1 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button1, 36);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -157);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "to2");

    ui_Button2 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button2, 36);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 158);
    lv_obj_set_y(ui_Button2, 1);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "to1");

    ui_Container4 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 268);
    lv_obj_set_height(ui_Container4, 266);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image35 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image35, &ui_img_1106867240);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image35, -82);
    lv_obj_set_y(ui_Image35, -74);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image35, 48);

    ui_Image36 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image36, &ui_img_253109117);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image36, -33);
    lv_obj_set_y(ui_Image36, -100);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image36, 48);

    ui_Image37 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image37, &ui_img_758318489);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image37, 21);
    lv_obj_set_y(ui_Image37, -102);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image37, 48);

    ui_Image38 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image38, &ui_img_154984886);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image38, 77);
    lv_obj_set_y(ui_Image38, -81);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image38, 48);

    ui_Image39 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image39, &ui_img_1951583080);
    lv_obj_set_width(ui_Image39, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image39, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image39, -36);
    lv_obj_set_y(ui_Image39, -46);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image39, 48);

    ui_Image40 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image40, &ui_img_1186072952);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image40, 6);
    lv_obj_set_y(ui_Image40, -46);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image40, 48);

    ui_Image41 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image41, &ui_img_1433976870);
    lv_obj_set_width(ui_Image41, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image41, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image41, 109);
    lv_obj_set_y(ui_Image41, -25);
    lv_obj_set_align(ui_Image41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image41, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image41, 48);

    ui_Image42 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image42, &ui_img_105594312);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image42, -10);
    lv_obj_set_y(ui_Image42, 37);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image42, 48);

    ui_Image43 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image43, &ui_img_1250489853);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image43, -103);
    lv_obj_set_y(ui_Image43, -21);
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image43, 48);

    ui_Image44 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image44, &ui_img_193771503);
    lv_obj_set_width(ui_Image44, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image44, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image44, -68);
    lv_obj_set_y(ui_Image44, 15);
    lv_obj_set_align(ui_Image44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image44, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image44, 48);

    ui_Image45 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image45, &ui_img_1251777188);
    lv_obj_set_width(ui_Image45, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image45, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image45, -102);
    lv_obj_set_y(ui_Image45, 46);
    lv_obj_set_align(ui_Image45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image45, 48);

    ui_Image46 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image46, &ui_img_647165550);
    lv_obj_set_width(ui_Image46, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image46, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image46, -61);
    lv_obj_set_y(ui_Image46, 77);
    lv_obj_set_align(ui_Image46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image46, 48);

    ui_Image47 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image47, &ui_img_918736298);
    lv_obj_set_width(ui_Image47, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image47, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image47, -15);
    lv_obj_set_y(ui_Image47, 100);
    lv_obj_set_align(ui_Image47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image47, 48);

    ui_Image49 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image49, &ui_img_1143713160);
    lv_obj_set_width(ui_Image49, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image49, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image49, 72);
    lv_obj_set_y(ui_Image49, 19);
    lv_obj_set_align(ui_Image49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image49, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image49, 48);

    ui_Image48 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image48, &ui_img_2024978968);
    lv_obj_set_width(ui_Image48, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image48, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image48, 26);
    lv_obj_set_y(ui_Image48, 64);
    lv_obj_set_align(ui_Image48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image48, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image48, 48);

    ui_Image50 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image50, &ui_img_754698310);
    lv_obj_set_width(ui_Image50, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image50, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image50, 91);
    lv_obj_set_y(ui_Image50, 65);
    lv_obj_set_align(ui_Image50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image50, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image50, 48);

    lv_obj_add_event_cb(ui_Label8, ui_event_Label8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label10, ui_event_Label10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
