// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1363077134);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image1, 1);
    lv_obj_set_y(ui_Image1, 10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 256);
    lv_obj_set_height(ui_Container1, 256);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image2, &ui_img_1861617944);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image3, &ui_img_1348765827);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image4, &ui_img_374812091);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image5, &ui_img_1112926375);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image6, &ui_img_1666228798);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image7, &ui_img_1861617944);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image8, &ui_img_658976223);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image9, &ui_img_1056724100);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image10, &ui_img_391371230);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image11, &ui_img_345343629);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image12, &ui_img_395471506);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image13, &ui_img_63016642);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
