// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

/*********************
 * @file ui_events.c
 * @brief 
 * @author LFG (lfg@.com)
 * @version 1.0
 * @date 2025-06-13
 * 
 * @copyright Copyright (c) 2025  LFG
 * 
 *************************************************/

#include "ui.h"
#include <time.h>
#include <stdlib.h>
#include <stdio.h>


/*********************
 * @brief 初始化全局emoji定时器和上一个显示索引
 *************************************************/
lv_timer_t *emoji_timer = NULL;
static uint8_t last_idx = 0;  // 初始化为无效索引

/*********************
 * @brief 定时器回调函数
 * @param  timer 定时器
 * @param idx 显示表情索引
 * @param last_idx 上一个显示索引
 * @details 获取定时器，获取父控件，获取父控件下子控件的个数
 *          生成一个范围在子控件个数内的随机索引，作为显示表情的索引，显示当前索引表情并隐藏上一个
 *          索引表情
 *************************************************/
static void emoji_change_timer_cb(lv_timer_t *timer)
{
    lv_obj_t *screen = (lv_obj_t *)timer->user_data;
    lv_obj_t * container = lv_obj_get_child(screen, 0);
    uint16_t child_cnt = lv_obj_get_child_cnt(container);
    
    if(child_cnt == 0) return;
    // 生成一个与上次不同的随机索引
    uint16_t idx;
    do {
        idx = rand() % child_cnt;
		printf("生成随机索引！：%d\n", idx);
    } while(idx == last_idx && child_cnt > 1);

    // 隐藏表情
    printf("last_idx 索引为 %d\n", last_idx);
    lv_obj_add_flag(lv_obj_get_child(container, last_idx), LV_OBJ_FLAG_HIDDEN);

    // 显示选中的表情
    lv_obj_t *curImage = lv_obj_get_child(container, idx);
    lv_obj_clear_flag(curImage, LV_OBJ_FLAG_HIDDEN);
    printf("显示表情！%d\n", idx);
    // 随机设置下一次切换的时间间隔（1-3秒）
    lv_timer_set_period(timer, 1000 + rand() % 2000);

    last_idx = idx;
}


/*********************
 * @brief 初始化随机数生成器，并创建定时器
 * @param  e 
 * @details 创建定时器，每一秒执行一次回调函数
 *************************************************/
void InitEmojiAutoChange(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    if(code != LV_EVENT_SCREEN_LOADED) return;  // 确保只在屏幕加载时执行一次
    if( code == LV_EVENT_SCREEN_LOADED )
    {
        lv_obj_t *screen = lv_event_get_target(e);
        srand(time(NULL));
        emoji_timer = lv_timer_create(emoji_change_timer_cb, 1000, screen);
        printf("创建定时器！\n"); 
    }
}


/*********************
 * @brief 初始化表情切换，并准备定时器
 * @param  e 
 *************************************************/
void InitScreenAutoChangeEmoji(lv_event_t * e)
{
	// Your code here
    lv_event_code_t code = lv_event_get_code(e);
    if( code == LV_EVENT_SCREEN_LOADED  )
    {
        printf("进行定时器！\n");
        InitEmojiAutoChange(e);
    }

}

void UnloadScreenAutoEmojiChange(lv_event_t * e)
{
	// Your code here
}





void InitUnLoad(lv_event_t * e)
{
	// Your code here
}
