// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

void emerge_Animation(lv_obj_t * TargetObject, int delay);
void leftout_Animation(lv_obj_t * TargetObject, int delay);
void rota_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1363077134);    // assets/保持安静的表情_1749443360.png
LV_IMG_DECLARE(ui_img_1861617944);    // assets/眨眼吐舌表情_1749726432.png
LV_IMG_DECLARE(ui_img_1348765827);    // assets/头晕表情_1749726418.png
LV_IMG_DECLARE(ui_img_374812091);    // assets/思考表情符号_1749443384.png
LV_IMG_DECLARE(ui_img_1112926375);    // assets/放松的表情_1749443347.png
LV_IMG_DECLARE(ui_img_1666228798);    // assets/爱心眼微笑_1749443366.png
LV_IMG_DECLARE(ui_img_658976223);    // assets/派对表情_1749443393.png
LV_IMG_DECLARE(ui_img_1056724100);    // assets/调皮的表情_1749726538.png
LV_IMG_DECLARE(ui_img_391371230);    // assets/流下喜悦泪水的猫咪_1749726487.png
LV_IMG_DECLARE(ui_img_345343629);    // assets/骷髅与交叉骨头_1749726527.png
LV_IMG_DECLARE(ui_img_395471506);    // assets/汗珠_1749726513.png
LV_IMG_DECLARE(ui_img_63016642);    // assets/不说话的猴子表情符号_1749726464.png
LV_IMG_DECLARE(ui_img_1782681216);    // assets/不满的猫咪_1749726476.png
LV_IMG_DECLARE(ui_img_1610904046);    // assets/倒立的脸_1749726456.png
LV_IMG_DECLARE(ui_img_473278995);    // assets/在地上打滚大笑的表情符号_1749443352.png
LV_IMG_DECLARE(ui_img_1799674937);    // assets/天使的微笑_1749726446.png
LV_IMG_DECLARE(ui_img_2119297200);    // assets/小丑的脸_1749726493.png
LV_IMG_DECLARE(ui_img_1468085881);    // assets/感受寒冷的脸_1749726499.png
LV_IMG_DECLARE(ui_img_2018771700);    // assets/爱心眼微笑_1749726441.png
LV_IMG_DECLARE(ui_img_459325315);    // assets/眯眼微笑的脸_1749443287.png
LV_IMG_DECLARE(ui_img_794820540);    // assets/脸红的表情符号_1749443374.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
