// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <time.h>
#include <stdlib.h>


// void Initialscreenandemojiautochange(lv_event_t * e)
// {
// 	lv_obj_t * code = lv_event_get_code(e);
// 	lv_obj_t * ta = lv_event_get_target(e);


// }

// void InitEmojiAutoChange(lv_event_t * e)
// {
// 	// Your code here
// 	lv_event_code_t code = lv_event_get_code(e);
// 	lv_obj_t * ta = lv_event_get_target(e);

// 	// lv_obj_t * contain = lv


// 	while( 1)
// 	{
// 		lv_obj_t * curImage = lv_obj_get_child(ta, rand()%10);
// 		lv_obj_clear_flag(curImage, LV_OBJ_FLAG_HIDDEN);
// 		sleep(rand()%3);
		
// 	}
	
// }


/*********************
 * @brief 
 *************************************************/
static lv_timer_t *emoji_timer = NULL;
static uint8_t last_idx = 255;  // 初始化为无效索引

static void emoji_change_timer_cb(lv_timer_t *timer)
{
    lv_obj_t *screen = (lv_obj_t *)timer->user_data;
    uint16_t child_cnt = lv_obj_get_child_cnt(screen);
    
    if(child_cnt == 0) return;
    
    // 生成一个与上次不同的随机索引
    uint16_t idx;
    do {
        idx = rand() % child_cnt;
    } while(idx == last_idx && child_cnt > 1);
    
    last_idx = idx;
    
    // 隐藏所有表情
    for(uint16_t i = 0; i < child_cnt; i++) {
        lv_obj_t *child = lv_obj_get_child(screen, i);
        lv_obj_add_flag(child, LV_OBJ_FLAG_HIDDEN);
    }
    
    // 显示选中的表情
    lv_obj_t *curImage = lv_obj_get_child(screen, idx);
    lv_obj_clear_flag(curImage, LV_OBJ_FLAG_HIDDEN);
    
    // 随机设置下一次切换的时间间隔（1-3秒）
    lv_timer_set_period(timer, 1000 + rand() % 2000);
}


void InitEmojiAutoChange(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code != LV_EVENT_READY) return;  // 确保只在屏幕加载时执行一次
    
    lv_obj_t *screen = lv_event_get_target(e);
    
    // 初始化随机数生成器（只需执行一次）
    srand(time(NULL));
    
    // 创建定时器，每1-3秒切换一次表情
    emoji_timer = lv_timer_create(emoji_change_timer_cb, 1000, screen);
}




void ClickEnterMainScreen(lv_event_t * e)
{
	// Your code here
}
